### PR TITLE
Loaded envs take precendence of existing envs

### PR DESCRIPTION
**Pull request by aaronjheng**

### CODE REVIEW

**Comment by mattn** [comment]
@joho this works fine for you too?

**Comment by joho** [comment]
Sure? Maybe?

It doesn't make sense in the underlying library because it's meant to provide defaults that can be overridden by more specific & production-like methods (ie actual env vars) but given this is more of a devtool than a production process runner it could be better ergonomics.

**Comment by mattn** [comment]
I prefer that we can override configuration via environment variable.

```
$ FOO=bar goreman
```

**Comment by joho** [comment]
If that's your preference you don't want this change then.

**Comment by mattn** [comment]
@joho Thanks your advice. @aaronjheng As I mentioned in above, I prefer to be possible to override with environment variable (not .env).

**Pull request closed without merging**
