### PR TITLE
Fix start panic with nil pointer dereference

### PR DESCRIPTION
**Pull request by aaronjheng**

### CODE REVIEW

**Comment by mattn** [comment]
Could you please explain how to reproduce?

**Comment by aaronjheng** [comment]
Just start with one or more procs (goreman start proc1).

**Comment by mattn** [comment]
Please try https://github.com/mattn/goreman/pull/94

**Comment by aaronjheng** [comment]
It works.

**Comment by mattn** [comment]
Thank you.

**Pull request closed without merging**
